version: 0.2

phases:
  pre_build:
    commands:
      - echo "Checking directory structure..."
      - ls -la  # Debug: see what files exist
      - echo "Installing dependencies..."
      - npm install  # Try root package.json first
      - if [ -d "client" ]; then cd client && npm install && cd ..; fi
      - if [ -d "server" ]; then cd server && npm install && cd ..; fi

  build:
    commands:
      - echo "Building application..."
      - if [ -d "client" ]; then cd client && npm run build && cd ..; fi
      - echo "Build completed"

  post_build:
    commands:
      - echo "Build completed on `date`"
      - ls -la  # Verify final structure

artifacts:
  files:
    - '**/*'
