version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies for static site"

  build:
    commands:
      - echo "Preparing static website build"
      - rm -rf build          # Clean old build folder
      - mkdir build
      - shopt -s extglob
      - cp -r !(build) build/
        
artifacts:
  files:
    - '**/*'
  base-directory: build
