version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies for static site"

  build:
    commands:
      - echo "Preparing static website build"
      - mkdir -p build
      - cp -r * build/

artifacts:
  files:
    - '**/*'
  base-directory: build
