version: 0.2

phases:
  install:
    commands:
      - echo "No dependencies for static site"
      - sudo yum install -y rsync
        
  build:
    commands:
      - echo "Preparing static website build"
      - rm -rf build
      - mkdir build
      - rsync -av --exclude='build' ./ ./build/

artifacts:
  files:
    - appspec.yml
    - '**/*'
